// ═══════════════════════════════════════════════════════════════════════════════
// MIA_StudyExplorer.cpp — Helper diagnostic temporaire (15/04/2026)
// ═══════════════════════════════════════════════════════════════════════════════
//
//   OBJECTIF
//   ---------
//   Dump toutes les etudes de tous les charts ouverts dans un fichier texte
//   pour identifier les charts sources / overlays dans le chartbook.
//
//   USAGE
//   -----
//     1. Compiler dans Sierra Chart (DLL separee "MIA Diagnostics") :
//          Analysis -> Studies -> Edit Study Data Files
//          -> Add -> MIA_StudyExplorer.cpp
//          -> Build -> Build All (la DLL "MIA Diagnostics.dll" apparait)
//
//     2. Attacher "MIA Study Explorer" a N'IMPORTE QUEL chart :
//          Analysis -> Studies -> MIA Diagnostics -> MIA Study Explorer -> Add
//
//     3. Attendre 1-2 secondes. Verifier le log :
//          Window -> Message Log
//          -> chercher "MIA StudyExplorer DONE: X charts, Y studies, Z overlays"
//
//     4. Recuperer le fichier :
//          C:\temp\mia_studies_dump.txt (prioritaire)
//        ou fallback :
//          C:\TRADING_SIERRA_CHART_AUTO\mia_studies_dump.txt
//
//     5. DETACHER l'etude apres usage (c'est un helper one-shot).
//
//   SORTIE
//   ------
//   Fichier texte contenant, pour chaque chart 1..100 :
//     - Numero de chart + symbole + nombre de barres
//     - Liste des etudes (ID + nom)
//     - Detection overlay via input 10 "Study to Overlay" :
//         [OVERLAY -> chart=X study=Y]   si decodage OK
//         [overlay_raw=Z]                si format inconnu
//
//   Auteur : MIA Trading System
//   Date   : 2026-04-15
// ═══════════════════════════════════════════════════════════════════════════════

#include "sierrachart.h"
#include <cstdio>

SCDLLName("MIA Diagnostics")

// ═══════════════════════════════════════════════════════════════════════════════
//  scsf_MIA_StudyExplorer : dump du chartbook complet
// ═══════════════════════════════════════════════════════════════════════════════

SCSFExport scsf_MIA_StudyExplorer(SCStudyInterfaceRef sc) {
    // ── Initialisation ──────────────────────────────────────────────────────
    if (sc.SetDefaults) {
        sc.GraphName = "MIA Study Explorer";
        sc.StudyDescription =
            "Dump chartbook complet (charts + studies + overlays) -> "
            "C:\\temp\\mia_studies_dump.txt. Usage one-shot : attacher, "
            "attendre log, detacher.";
        sc.AutoLoop = 1;
        sc.UpdateAlways = 0;
        sc.FreeDLL = 0;
        sc.GraphRegion = 0;
        return;
    }

    // ── One-shot : n'executer qu'une seule fois par session ───────────────
    int& already_dumped = sc.GetPersistentInt(1);
    if (already_dumped == 1) return;

    // On ne dump qu'a la derniere barre (garantit que tous les charts sont charges)
    if (sc.Index != sc.ArraySize - 1) return;

    already_dumped = 1;

    // ── Ouverture du fichier de sortie ──────────────────────────────────────
    const char* output_path_primary  = "C:\\temp\\mia_studies_dump.txt";
    const char* output_path_fallback = "C:\\TRADING_SIERRA_CHART_AUTO\\mia_studies_dump.txt";
    const char* output_path = output_path_primary;

    FILE* f = fopen(output_path, "w");
    if (!f) {
        output_path = output_path_fallback;
        f = fopen(output_path, "w");
        if (!f) {
            sc.AddMessageToLog(
                "MIA StudyExplorer: CANNOT OPEN OUTPUT FILE "
                "(ni C:\\temp ni C:\\TRADING_SIERRA_CHART_AUTO)", 1);
            return;
        }
    }

    // ── En-tete ─────────────────────────────────────────────────────────────
    fprintf(f, "================================================================\n");
    fprintf(f, "  MIA STUDY EXPLORER - CHARTBOOK DUMP\n");
    fprintf(f, "  Generated by scsf_MIA_StudyExplorer\n");
    fprintf(f, "================================================================\n\n");

    int total_charts   = 0;
    int total_studies  = 0;
    int total_overlays = 0;

    // ── Boucle sur les charts 1..100 ────────────────────────────────────────
    for (int chartNum = 1; chartNum <= 100; chartNum++) {

        // Test d'existence : tenter de lire le tableau close du chart
        SCFloatArray closeArr;
        sc.GetChartArray(chartNum, SC_LAST, closeArr);
        const int barCount = closeArr.GetArraySize();
        if (barCount == 0) continue;  // Chart inexistant ou vide

        total_charts++;

        // Symbole du chart
        SCString symbol = sc.GetChartSymbol(chartNum);

        fprintf(f, "\n================================================================\n");
        fprintf(f, "CHART #%d\n", chartNum);
        fprintf(f, "  Symbol : %s\n", symbol.GetLength() > 0 ? symbol.GetChars() : "<unknown>");
        fprintf(f, "  Bars   : %d\n", barCount);
        fprintf(f, "================================================================\n");

        // Boucle sur les studies 1..300
        int studies_in_chart = 0;
        for (int studyID = 1; studyID <= 300; studyID++) {

            // Signature ACSIL : SCString sc.GetStudyNameFromChart(chart, studyID) -> return SCString
            SCString studyName = sc.GetStudyNameFromChart(chartNum, studyID);

            if (studyName.GetLength() == 0) continue;  // Study inexistante

            total_studies++;
            studies_in_chart++;

            fprintf(f, "  ID:%-3d  %s", studyID, studyName.GetChars());

            // Detection overlay : lecture de l'input 10 "Study to Overlay"
            // Signature ACSIL : int sc.GetChartStudyInputInt(chart, studyID, inputIdx, int& out) -> return code (1=ok)
            // Format ACSIL : encodage variable selon version SC.
            // On tente plusieurs decodages et on dump le raw en cas d'inconnu.
            int overlayRaw = 0;
            sc.GetChartStudyInputInt(chartNum, studyID, 10, overlayRaw);

            if (overlayRaw > 0) {
                // Tentative 1 : format chart * 100000 + studyID
                int srcChart1 = overlayRaw / 100000;
                int srcStudy1 = overlayRaw % 100000;

                // Tentative 2 : format chart * 1000 + studyID
                int srcChart2 = overlayRaw / 1000;
                int srcStudy2 = overlayRaw % 1000;

                bool decoded = false;

                if (srcChart1 >= 1 && srcChart1 <= 100
                    && srcStudy1 >= 1 && srcStudy1 <= 300) {
                    fprintf(f, "  [OVERLAY -> chart=%d study=%d (fmt:100000)]",
                            srcChart1, srcStudy1);
                    total_overlays++;
                    decoded = true;
                } else if (srcChart2 >= 1 && srcChart2 <= 100
                           && srcStudy2 >= 1 && srcStudy2 <= 300) {
                    fprintf(f, "  [OVERLAY -> chart=%d study=%d (fmt:1000)]",
                            srcChart2, srcStudy2);
                    total_overlays++;
                    decoded = true;
                }

                if (!decoded) {
                    fprintf(f, "  [input10_raw=%d]", overlayRaw);
                }
            }

            fprintf(f, "\n");
        }

        if (studies_in_chart == 0) {
            fprintf(f, "  (aucune etude attachee)\n");
        }
    }

    // ── Resume final ────────────────────────────────────────────────────────
    fprintf(f, "\n================================================================\n");
    fprintf(f, "  TOTAL : %d charts | %d studies | %d overlays decodes\n",
            total_charts, total_studies, total_overlays);
    fprintf(f, "================================================================\n");
    fprintf(f, "\n");
    fprintf(f, "NOTE : si un overlay apparait en [input10_raw=X], cela signifie\n");
    fprintf(f, "       que le format d'encodage n'est pas reconnu. Reporter le\n");
    fprintf(f, "       raw a Claude pour decodage manuel.\n");
    fprintf(f, "\n");
    fprintf(f, "NOTE : les features mortes dans le DMP (fp_edge_*, bar_edge_*,\n");
    fprintf(f, "       bn_absorb_*) viennent des etudes qui sont des OVERLAYS.\n");
    fprintf(f, "       Le vrai chart source est celui indique [OVERLAY -> chart=X].\n");

    fclose(f);

    // ── Notification finale ────────────────────────────────────────────────
    SCString msg;
    msg.Format(
        "MIA StudyExplorer DONE: %d charts, %d studies, %d overlays -> %s",
        total_charts, total_studies, total_overlays, output_path);
    sc.AddMessageToLog(msg, 1);
}

// ═══════════════════════════════════════════════════════════════════════════════
// FIN MIA_StudyExplorer.cpp
// ═══════════════════════════════════════════════════════════════════════════════
